fedavg_blades:
  run: FEDAVG_debug
  stop:
    training_iteration: 100
    # train_loss: 100000

  config:
    random_seed:
        grid_search: [122]
      # grid_search: [121, 122, 123, 124, 125]
    dataset_config:
      type: CIFAR10
      num_clients: 61
      train_batch_size: 64

      partitioner_config:
        type: DirichletPartitioner
        alpha:
          grid_search: [10]
        num_clients: 61

    evaluation_interval: 50

    num_remote_workers: 0
    num_gpus_per_worker: 0.3
    num_cpus_per_worker: 0
    num_cpus_for_driver: 4
    num_gpus_for_driver: 0.3

    # num_remote_workers: 14
    # num_gpus_per_worker: 0.25
    # num_cpus_per_worker: 2
    # num_cpus_for_driver: 2
    # num_gpus_for_driver: 0.5

    # num_clients: 2
    # global_model:
      # grid_search: [cct]
    # global_model: cct
    global_model: resnet
    # global_model: cnn

    client_config:
        lr: 1.0
        momentum:
          grid_search: [0.0]

    server_config:
      aggregator:
        grid_search: 
          - type: Median
          - type: Trimmedmean
          - type: Signguard
          - type: Multikrum
          - type: blades.aggregators.EnsembleAggregator
            aggregators_config: 
            - name: Median
            - name: Trimmedmean
            - name: Signguard
            - name: Multikrum
          - type: blades.aggregators.RandomEnsembleAggregator
            aggregators_config: 
            - name: Median
            - name: Trimmedmean
            - name: Signguard
            - name: Multikrum

      optimizer:
        type: SGD
        lr: 0.1
        # lr_schedule: [[0, 0.1], [1500, 0.1], [1501, 0.01], [2000, 0.01]]
        # lr: 0.1
        # lr_schedule: [[0, 0.1], [1500, 0.1],  [1501, 0.05], [3000, 0.05], [3001, 0.005], [4000, 0.005]]
        momentum:
          grid_search: [0.0]

    num_malicious_clients:
      # grid_search: [6]
      grid_search: [0, 6, 9, 12, 15, 18]
      # grid_search: [3, 6, 9, 12, 15, 18, 21]
    adversary_config:
      # type: blades.adversaries.LabelFlipAdversary
      grid_search:
        - type: blades.adversaries.ALIEAdversary
        - type: blades.adversaries.LabelFlipAdversary
        - type: blades.adversaries.NoiseAdversary
        - type: blades.adversaries.SignFlipAdversary
        - type: blades.adversaries.AdaptiveAdversary
        - type: blades.adversaries.IPMAdversary
          scale: 0.1
        - type: blades.adversaries.IPMAdversary
          scale: 100
