fedavg_blades_v2:
  run: FEDAVG
  stop:
    training_iteration: 200

  config:
    random_seed:
      # grid_search: [121, 122, 123, 124, 125]
      grid_search: [121]
    dataset_config:
      type: CIFAR10
      num_clients: 60
      num_classes: 10
      train_batch_size: 64

      partitioner_config:
        type: DirichletPartitioner
        alpha: 100.
        num_clients: 60

    evaluation_interval: 50

    num_remote_workers: 0
    num_gpus_per_worker: 1
    num_cpus_per_worker: 0
    num_cpus_for_driver: 4
    num_gpus_for_driver: 1

    global_model: resnet

    client_config:
        lr: 1.0
        momentum:
          grid_search: [0.0]

        # callbacks_config:
        #   type: blades.clients.callbacks.ClippingCallback
        #   clip_threshold:
        #     grid_search: [5.0]

    server_config:
      aggregator:
        grid_search:
        - type: Median
        - type: Trimmedmean
        - type: Signguard
        - type: Multikrum
          # type: Clippedclustering,
          # type: Median,
        - type: blades.aggregators.EnsembleAggregator
          aggregators_config: 
          - name: Median
          - name: Trimmedmean
          - name: Signguard
          - name: Multikrum
        - type: blades.aggregators.RandomEnsembleAggregator
          aggregators_config: 
          - name: Median
          - name: Trimmedmean
          - name: Signguard
          - name: Multikrum
          # type: GeoMed,
          # type: DnC,
          # type: Trimmedmean,
          # type: Signguard,
          # type: Multikrum,
          # type: Centeredclipping
        

      optimizer:
        type: SGD
        lr: 0.1
        # lr_schedule: []
        momentum:
          grid_search: [0.0]

    num_malicious_clients:
      grid_search:  [0, 6, 12, 18, 24, 30]
      # grid_search:  [26, 9]
      # grid_search:  [3, 6, 9, 12, 15, 18]

    adversary_config:
      grid_search:
        - type: blades.adversaries.ALIEAdversary
        - type: blades.adversaries.LabelFlipAdversary
        - type: blades.adversaries.NoiseAdversary
        - type: blades.adversaries.SignFlipAdversary
        - type: blades.adversaries.IPMAdversary
          scale: 0.1
        - type: blades.adversaries.IPMAdversary
          scale: 100
        - type: blades.adversaries.MinMaxAdversary
